Practical 6
desaianiruddh/React-practical pull request #6
Opened 2022-03-21 12:44 UTC by desaianiruddh

2022-03-22 10:48 UTC, harshpatel-javascript commented on user-list-prac-6/src/App.jsx
> +                Just Sec...Page is Loading
keep identation same( ex. space betweeen = )

2022-03-22 10:51 UTC, harshpatel-javascript commented on user-list-prac-6/src/components/ProfileCard/profileCard.css
> +              0px 6px 20px 0px rgba(0, 0, 0, 0.19);
keep same color methods in all files.
rgba -> hex

2022-03-22 10:52 UTC, harshpatel-javascript commented on user-list-prac-6/src/components/ProfileList/profileList.css
> +		display: flex;
identation issues

2022-03-23 08:22 UTC, Rutvi25 requested changes

2022-03-23 08:22 UTC, Rutvi25 commented on user-list-prac-6/src/components/ProfileCard/profileCard.css
> +.active-dot {
only one property is different in active and inactive-dot classes, so we can merge that part.

2022-03-23 10:39 UTC, harshpatel-javascript approved these changes

2022-03-23 10:57 UTC, Rutvi25 approved these changes

2022-03-28 15:11 UTC, sheth-jay commented on user-list-prac-6/src/App.jsx
> +          <ChangePage />
move this ChangePage component inside ProfileList and rename it to Pagination.

2022-03-28 15:11 UTC, sheth-jay commented on user-list-prac-6/src/actions/index.js
> +      const userPage1 = await axios.get('https://reqres.in/api/users?page=1');
This implementation approach is incorrect . Initially fetch data for the first page and on page change fetch data for that page.

2022-03-28 15:11 UTC, sheth-jay commented on user-list-prac-6/src/actions/index.js
> +export const setDataToState = (userDataPage1, userDataPage2) => {
this action should be renamed to fetchUserSuccess.

2022-03-28 15:11 UTC, sheth-jay commented on user-list-prac-6/src/actions/index.js
> +
remove unnecessary lines

2022-03-28 15:11 UTC, sheth-jay commented on user-list-prac-6/src/components/EmployeeList/EmployeeList.jsx
> +    status === 'inactive'
change to status === 'active'.

2022-03-28 15:11 UTC, sheth-jay commented on user-list-prac-6/src/components/Pagination/ChangePage.jsx
> +        <li
this list item should be rendered using map instead of single item at a time. Suppose you have 20 pages then you will repeat same code for 20 times.

2022-03-28 15:11 UTC, sheth-jay commented on user-list-prac-6/src/components/ProfileCard/profileCard.css
> +  background-color: #008000;
move this line to above active and inactive dot class selector and then you can omit this .active-dot selector.

2022-03-28 15:11 UTC, sheth-jay commented on user-list-prac-6/src/components/ProfileList/profileList.css
> +td:first-child {
remove this and do something like
     `<th style="width: 30%">Col 1</th>`
     `<th style="width: 20%">Col 2</th>`
      `<th style="width: 10%">Col 3</th>`

2022-03-28 15:11 UTC, sheth-jay commented on user-list-prac-6/src/components/ProfileList/profileList.css
> +@media only screen and (max-width: 970px) {
use appropriate breakpoints. e.g. 576, 768, 992, 1200.

2022-03-28 15:11 UTC, sheth-jay commented on user-list-prac-6/src/components/ProfileList/profileList.css
> +@media only screen and (max-width: 970px) {
use appropriate breakpoints. e.g. 576, 768, 992, 1200.

2022-04-01 04:43 UTC, sheth-jay approved these changes

2022-04-01 04:43 UTC, merged