Practical-8
desaianiruddh/React-practical pull request #7
Opened 2022-04-06 05:38 UTC by desaianiruddh

2022-04-06 09:32 UTC, Rutvi25 commented on user-management-react-app/src/App.js
> +        <Route path="/" element={<SignUp />} />
path name should be "signup" for signup page

2022-04-06 09:32 UTC, Rutvi25 commented on user-management-react-app/src/components/UserCard/UserCard.jsx
> +  console.log(userData);
remove logs

2022-04-06 09:32 UTC, Rutvi25 commented on user-management-react-app/src/reducers/userData.js
> +    case 'SUBMIT_FORM': {
no need of {},
you can directly write return statement
case 'SUBMIT_FORM':
  return {
  ...
  };

2022-04-06 09:36 UTC, Rutvi25 requested changes

2022-04-06 09:36 UTC, Rutvi25 commented on user-management-react-app/src/App.js
> +        <Route path="/" element={<SignUp />} />
path name should be "signup" for signup page

2022-04-06 09:36 UTC, Rutvi25 commented on user-management-react-app/src/components/UserCard/UserCard.jsx
> +  console.log(userData);
remove logs

2022-04-07 04:53 UTC, Rutvi25 approved these changes

2022-04-07 09:15 UTC, harshpatel-javascript approved these changes

2022-04-08 04:27 UTC, sheth-jay requested changes

2022-04-08 04:27 UTC, sheth-jay commented on user-management-react-app/src/actions/index.js
> +      profilePhoto: URL.createObjectURL(values.profilePhoto),
This should be done inside OnSubmit function.

2022-04-08 04:27 UTC, sheth-jay commented on user-management-react-app/src/actions/index.js
> +    type: 'SUBMIT_FORM',
Change action name to something more meaningful name. As in future you may have multiple forms at that time SUBMIT_FORM will be confusing.

2022-04-08 04:27 UTC, sheth-jay commented on user-management-react-app/src/components/Pages/SignUp/SignUp.jsx
> +        window.innerWidth > 1048
Always use appropriate break points.

2022-04-08 06:00 UTC, sheth-jay approved these changes

2022-04-11 11:02 UTC, merged